const fakeCourses = [
    {
      id: 1,
      name: 'Web Development Fundamentals',
      instructor: 'Jane Smith',
      description: 'Learn the basics of web development.',
      enrollmentStatus: 'Open',
      thumbnail: 'course1.jpg',
      duration: '6 weeks',
      schedule: 'Mondays and Wednesdays, 6:00 PM - 8:00 PM',
      location: 'Online',
      price: 199.99, // Price in USD
      full: true,
      syllabus: [
        { topic: 'Introduction to HTML', weeks: 0 },
        { topic: 'CSS Styling', weeks: 1 },
        { topic: 'JavaScript Fundamentals', weeks: 2 },
        { topic: 'Responsive Web Design', weeks: 3 },
      ],
    },
    {
      id: 2,
      name: 'Data Science Essentials',
      instructor: 'David Johnson',
      description: 'Explore the fundamentals of data science.',
      enrollmentStatus: 'Open',
      thumbnail: 'course2.jpg',
      duration: '10 weeks',
      schedule: 'Tuesdays and Thursdays, 7:00 PM - 9:00 PM',
      location: 'Online',
      price: 249.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Introduction to Data Science', weeks: 0 },
        { topic: 'Data Analysis and Visualization', weeks: 1 },
        { topic: 'Machine Learning', weeks: 2 },
        { topic: 'Big Data and Data Engineering', weeks: 3 },
      ],
    },
    {
      id: 3,
      name: 'Graphic Design for Beginners',
      instructor: 'Amy Wilson',
      description: 'Start your journey into the world of graphic design.',
      enrollmentStatus: 'Open',
      thumbnail: 'course3.jpg',
      duration: '8 weeks',
      schedule: 'Fridays, 6:30 PM - 9:30 PM',
      location: 'In-Person',
      price: 149.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Introduction to Graphic Design', weeks: 0 },
        { topic: 'Typography and Layout', weeks: 1 },
        { topic: 'Image Editing with Photoshop', weeks: 2 },
        { topic: 'Logo Design', weeks: 3 },
      ],
    },
    {
      id: 4,
      name: 'Machine Learning and AI',
      instructor: 'Michael Brown',
      description: 'Dive into the world of machine learning and artificial intelligence.',
      enrollmentStatus: 'Open',
      thumbnail: 'course4.jpg',
      duration: '12 weeks',
      schedule: 'Saturdays, 10:00 AM - 12:00 PM',
      location: 'Online',
      price: 299.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Introduction to Machine Learning', weeks: 0 },
        { topic: 'Deep Learning', weeks: 1 },
        { topic: 'Computer Vision', weeks: 2 },
        { topic: 'Natural Language Processing', weeks: 3 },
      ],
    },
    {
      id: 5,
      name: 'Digital Marketing Masterclass',
      instructor: 'Laura Taylor',
      description: 'Learn advanced digital marketing strategies.',
      enrollmentStatus: 'Open',
      thumbnail: 'course5.jpg',
      duration: '9 weeks',
      schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
      location: 'Online',
      price: 199.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Digital Marketing Fundamentals', weeks: 0 },
        { topic: 'Social Media Marketing', weeks: 1 },
        { topic: 'Content Marketing', weeks: 2 },
        { topic: 'SEO and SEM', weeks: 3 },
      ],
    },
    {
      id: 6,
      name: 'Mobile App Development with Flutter',
      instructor: 'Mark Anderson',
      description: 'Build mobile apps with Flutter framework.',
      enrollmentStatus: 'Open',
      thumbnail: 'course6.jpg',
      duration: '7 weeks',
      schedule: 'Tuesdays and Thursdays, 6:30 PM - 8:30 PM',
      location: 'Online',
      price: 249.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Introduction to Flutter', weeks: 0 },
        { topic: 'Dart Programming', weeks: 1 },
        { topic: 'UI Design with Flutter', weeks: 2 },
        { topic: 'Building Apps with Flutter', weeks: 3 },
      ],
    },
    {
      id: 7,
      name: 'Introduction to Python Programming',
      instructor: 'Chris Evans',
      description: 'Get started with Python programming language.',
      enrollmentStatus: 'Open',
      thumbnail: 'course7.jpg',
      duration: '5 weeks',
      schedule: 'Saturdays, 1:00 PM - 3:00 PM',
      location: 'Online',
      price: 149.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Python Basics', weeks: 0 },
        { topic: 'Control Structures', weeks: 1 },
        { topic: 'Functions and Modules', weeks: 2 },
        { topic: 'Final Project', weeks: 3 },
      ],
    },
    {
      id: 8,
      name: 'Artificial Intelligence Ethics',
      instructor: 'Emily White',
      description: 'Explore the ethical implications of AI.',
      enrollmentStatus: 'Open',
      thumbnail: 'course8.jpg',
      duration: '6 weeks',
      schedule: 'Thursdays, 5:00 PM - 7:00 PM',
      location: 'In-Person',
      price: 199.99, // Price in USD
      full: true,
      syllabus: [
        { topic: 'Introduction to AI Ethics', weeks: 0 },
        { topic: 'Ethical Dilemmas', weeks: 1 },
        { topic: 'AI Regulations', weeks: 2 },
        { topic: 'Final Ethics Project', weeks: 3 },
      ],
    },
    {
      id: 9,
      name: 'Digital Photography Workshop',
      instructor: 'Daniel Lee',
      description: 'Learn photography techniques and skills.',
      enrollmentStatus: 'Open',
      thumbnail: 'course9.jpg',
      duration: '4 weeks',
      schedule: 'Sundays, 9:00 AM - 12:00 PM',
      location: 'In-Person',
      price: 149.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Photography Basics', weeks: 0 },
        { topic: 'Composition and Lighting', weeks: 1 },
        { topic: 'Editing and Post-Processing', weeks: 2 },
        { topic: 'Photography Portfolio', weeks: 3 },
      ],
    },
    {
      id: 10,
      name: 'UI/UX Design for Mobile Apps',
      instructor: 'Olivia Brown',
      description: 'Design user-friendly mobile app interfaces.',
      enrollmentStatus: 'Open',
      thumbnail: 'course10.jpg',
      duration: '7 weeks',
      schedule: 'Mondays and Wednesdays, 6:30 PM - 8:30 PM',
      location: 'Online',
      price: 199.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'UI Design Principles', weeks: 0 },
        { topic: 'User Experience (UX) Design', weeks: 1 },
        { topic: 'Prototyping and Usability Testing', weeks: 2 },
        { topic: 'Mobile App Design Project', weeks: 3 },
      ],
    },
    {
      id: 11,
      name: 'Introduction to Game Development',
      instructor: 'Peter Clark',
      description: 'Start your journey into game development.',
      enrollmentStatus: 'Open',
      thumbnail: 'course11.jpg',
      duration: '8 weeks',
      schedule: 'Tuesdays and Thursdays, 7:00 PM - 9:00 PM',
      location: 'Online',
      price: 249.99, // Price in USD
      full: true,
      syllabus: [
        { topic: 'Game Design Principles', weeks: 0 },
        { topic: 'Unity Basics', weeks: 1 },
        { topic: '2D Game Development', weeks: 2 },
        { topic: '3D Game Development', weeks: 3 },
      ],
    },
    {
      id: 12,
      name: 'Blockchain and Cryptocurrency',
      instructor: 'Sarah Miller',
      description: 'Explore the world of blockchain technology.',
      enrollmentStatus: 'Open',
      thumbnail: 'course12.jpg',
      duration: '10 weeks',
      schedule: 'Fridays, 6:00 PM - 8:00 PM',
      location: 'Online',
      price: 299.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Introduction to Blockchain', weeks: 0 },
        { topic: 'Cryptocurrency Fundamentals', weeks: 1 },
        { topic: 'Smart Contracts and DApps', weeks: 2 },
        { topic: 'Blockchain Project', weeks: 3 },
      ],
    },
    {
      id: 13,
      name: 'English Literature Classics',
      instructor: 'Thomas Davis',
      description: 'Study classic works of English literature.',
      enrollmentStatus: 'Open',
      thumbnail: 'course13.jpg',
      duration: '12 weeks',
      schedule: 'Saturdays, 2:00 PM - 4:00 PM',
      location: 'In-Person',
      price: 199.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Shakespearean Literature', weeks: 0 },
        { topic: 'Romantic Poetry', weeks: 1 },
        { topic: 'Victorian Novels', weeks: 2 },
        { topic: 'Modernist Literature', weeks: 3 },
      ],
    },
    {
      id: 14,
      name: 'Introduction to Cybersecurity',
      instructor: 'Ella Wilson',
      description: 'Learn the basics of cybersecurity and online safety.',
      enrollmentStatus: 'Open',
      thumbnail: 'course14.jpg',
      duration: '6 weeks',
      schedule: 'Thursdays, 6:30 PM - 8:30 PM',
      location: 'In-Person',
      price: 149.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Cybersecurity Fundamentals', weeks: 0 },
        { topic: 'Network Security', weeks: 1 },
        { topic: 'Ethical Hacking', weeks: 2 },
        { topic: 'Security Practices', weeks: 3 },
      ],
    },
    {
      id: 15,
      name: 'Music Production and Composition',
      instructor: 'William Johnson',
      description: 'Create music and compose your own tunes.',
      enrollmentStatus: 'Open',
      thumbnail: 'course15.jpg',
      duration: '8 weeks',
      schedule: 'Sundays, 3:00 PM - 5:00 PM',
      location: 'In-Person',
      price: 199.99, // Price in USD
      full: false,
      syllabus: [
        { topic: 'Music Theory', weeks: 0 },
        { topic: 'Digital Audio Workstations (DAWs)', weeks: 1 },
        { topic: 'Composition Techniques', weeks: 2 },
        { topic: 'Music Production Project', weeks: 3 },
      ],
    },
    {
      id: 16,
      name: 'Art History: Renaissance to Modern',
      instructor: 'Sophia Martin',
      description: 'Explore the history of art from the Renaissance to modern times.',
      enrollmentStatus: 'Open',
      thumbnail: 'course16.jpg',
      duration: '10 weeks',
      schedule: 'Mondays and Wednesdays, 5:00 PM - 7:00 PM',
      location: 'Online',
      price: 249.99, // Price in USD
      full: false,
      progress: 50,
      syllabus: [
        { topic: 'Renaissance Art', weeks: 0 },
        { topic: 'Baroque and Rococo', weeks: 1 },
        { topic: '19th-Century Art', weeks: 2 },
        { topic: 'Modern Art Movements', weeks: 3 },
      ],
    },
]

export default fakeCourses;